import { ScaledSheet, moderateScale } from 'react-native-size-matters';

import { colors, gradients } from '../../theme';

export const styles = ScaledSheet.create({
  screen: {
    flex: 1,
  },
  chat: {
    flex: 1,
    paddingHorizontal: moderateScale(16),
  },
  chatContent: {
    gap: moderateScale(14),
    paddingTop: moderateScale(28),
    paddingBottom: moderateScale(16),
  },
  parsingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(8),
    marginLeft: moderateScale(40),
  },
  parsingText: {
    fontSize: moderateScale(14),
    fontWeight: '400',
    color: colors.textCaption,
  },
  nextSection: {
    marginLeft: moderateScale(40),
    width: moderateScale(272),
    gap: moderateScale(12),
  },
  nextTitle: {
    fontSize: moderateScale(14),
    fontWeight: '400',
    color: colors.textPrimary,
  },
  nextActions: {
    flexDirection: 'row',
    gap: moderateScale(16),
  },
  footer: {
    backgroundColor: colors.surface,
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: colors.borderLight,
    paddingTop: moderateScale(16),
    paddingBottom: moderateScale(14),
    paddingHorizontal: moderateScale(16),
    gap: moderateScale(12),
  },
  composerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(8),
  },
  composerTitle: {
    flex: 1,
    fontSize: moderateScale(16),
    fontWeight: '500',
    color: colors.textPrimary,
  },
  inputWrap: {
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: colors.borderMuted,
    padding: moderateScale(12),
    paddingTop: moderateScale(8),
    backgroundColor: colors.surface,
    paddingRight: moderateScale(60),
  },
  input: {
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
    color: colors.textPrimary,
    minHeight: moderateScale(80),
    textAlignVertical: 'top',
  },
  sendButton: {
    position: 'absolute',
    right: moderateScale(12),
    bottom: moderateScale(12),
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(12),
    alignItems: 'center',
    justifyContent: 'center',
    experimental_backgroundImage: gradients.brand,
    boxShadow: '0px 2px 4px rgba(99, 99, 99, 0.16)',
  },
  chips: {
    flexDirection: 'row',
    gap: moderateScale(12),
  },
  chip: {
    flex: 1,
    minHeight: moderateScale(30),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: moderateScale(10),
    paddingVertical: moderateScale(5),
    backgroundColor: colors.surfaceMuted,
    borderRadius: moderateScale(12),
  },
  chipLabel: {
    fontSize: moderateScale(12),
    fontWeight: '400',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  scroll: {
    flex: 1,
  },
  header: {
    marginHorizontal: moderateScale(16),
  },
  scrollContent: {
    gap: moderateScale(16),
    paddingTop: moderateScale(12),
    paddingBottom: moderateScale(24),
    paddingHorizontal: moderateScale(16),
  },
  card: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: moderateScale(12),
    padding: moderateScale(16),
    gap: moderateScale(18),
    boxShadow: '0px 2px 4px rgba(99, 99, 99, 0.08)',
  },
  vialCard: {
    flexDirection: 'row',
    gap: moderateScale(44),
    backgroundColor: colors.surfaceMuted,
    borderRadius: moderateScale(12),
    paddingVertical: moderateScale(18),
    paddingHorizontal: moderateScale(16),
    minHeight: moderateScale(191),
    boxShadow: '0px 2px 4px rgba(99, 99, 99, 0.08)',
  },
  vialVisual: {
    width: moderateScale(95),
    alignItems: 'center',
  },
  vialCap: {
    width: moderateScale(89),
    height: moderateScale(24),
    borderRadius: moderateScale(6),
    backgroundColor: colors.borderMuted,
  },
  vialNeck: {
    width: moderateScale(40),
    height: moderateScale(10),
    backgroundColor: colors.borderLight,
  },
  vialBody: {
    width: moderateScale(95),
    height: moderateScale(115),
    borderRadius: moderateScale(12),
    borderWidth: 2,
    borderColor: colors.borderMuted,
    overflow: 'hidden',
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  vialFill: {
    height: moderateScale(61),
    alignItems: 'center',
    justifyContent: 'center',
    gap: moderateScale(2),
    borderBottomLeftRadius: moderateScale(10),
    borderBottomRightRadius: moderateScale(10),
  },
  vialFillLabel: {
    fontSize: moderateScale(18),
    fontWeight: '600',
    color: colors.surface,
    lineHeight: moderateScale(26),
  },
  vialFillDose: {
    fontSize: moderateScale(14),
    fontWeight: '500',
    color: colors.surface,
    lineHeight: moderateScale(22),
  },
  vialMeta: {
    flex: 1,
    justifyContent: 'space-between',
    paddingTop: moderateScale(0),
    paddingBottom: moderateScale(8),
  },
  vialStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  vialStat: {
    gap: moderateScale(2),
    minWidth: moderateScale(51),
  },
  vialStatLabel: {
    fontSize: moderateScale(16),
    fontWeight: '400',
    color: colors.textPrimary,
    lineHeight: moderateScale(24),
  },
  vialStatValue: {
    fontSize: moderateScale(16),
    fontWeight: '500',
    color: colors.textPrimary,
    lineHeight: moderateScale(24),
  },
  colorSection: {
    gap: moderateScale(8),
  },
  colorLabel: {
    fontSize: moderateScale(16),
    fontWeight: '400',
    color: colors.textPrimary,
    lineHeight: moderateScale(24),
  },
  colorRow: {
    flexDirection: 'row',
    gap: moderateScale(6),
  },
  colorSwatch: {
    width: moderateScale(34),
    height: moderateScale(34),
    borderRadius: moderateScale(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  unitField: {
    gap: moderateScale(12),
  },
  fieldLabel: {
    fontSize: moderateScale(16),
    fontWeight: '400',
    color: colors.textPrimary,
    lineHeight: moderateScale(20),
  },
  unitInput: {
    height: moderateScale(52),
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(10),
    paddingHorizontal: moderateScale(12),
    backgroundColor: colors.surface,
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: colors.borderMuted,
  },
  unitPrefix: {
    fontSize: moderateScale(16),
    fontWeight: '400',
    color: colors.textMuted,
    lineHeight: moderateScale(24),
  },
  unitValue: {
    flex: 1,
    fontSize: moderateScale(16),
    fontWeight: '400',
    color: colors.textPrimary,
    lineHeight: moderateScale(20),
    padding: 0,
    margin: 0,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  selectField: {
    height: moderateScale(52),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(12),
    backgroundColor: colors.surface,
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: colors.borderMuted,
    gap: moderateScale(8),
  },
  selectValue: {
    flex: 1,
    fontSize: moderateScale(16),
    fontWeight: '400',
    color: colors.textPrimary,
    lineHeight: moderateScale(24),
  },
  chevron: {
    transform: [{ rotate: '180deg' }],
  },
});
